package main

import (
	"bytes"
	"flag"
	"fmt"
	"io"
	"log"
	"os"
	"strings"

	"github.com/lindell/string-enumer/pkg/stringenumer"
)

var (
	typeNames  = flag.String("type", "", "comma-separated list of type names; must be set")
	text       = flag.Bool("text", false, "if true, text marshaling methods will be generated. Default: false")
	outputPath = flag.String("output", "", "output file name; default srcdir/<type>_enumer.go")
)

// Usage is a replacement usage function for the flags package.
func Usage() {
	fmt.Fprintf(os.Stderr, "Usage of string-enumer:\n")
	fmt.Fprintf(os.Stderr, "\tstring-enumer [flags] -type T [directory]\n")
	fmt.Fprintf(os.Stderr, "\tstring-enumer [flags] -type T files... # Must be a single package\n")
	fmt.Fprintf(os.Stderr, "For more information, see:\n")
	fmt.Fprintf(os.Stderr, "\thttps://github.com/lindell/string-enumer\n")
	fmt.Fprintf(os.Stderr, "Flags:\n")
	flag.PrintDefaults()
}

func main() {
	flag.Usage = Usage
	flag.Parse()

	if len(*typeNames) == 0 {
		flag.Usage()
		os.Exit(2)
	}

	args := flag.Args()
	if len(args) == 0 {
		flag.Usage()
		os.Exit(2)
	}

	types := strings.Split(*typeNames, ",")

	r, err := stringenumer.Generate(
		stringenumer.Paths(args...),
		stringenumer.TypeNames(types...),
		stringenumer.TextUnmarshaling(*text),
	)
	if err != nil {
		log.Fatalln(err)
	}

	var output io.Writer
	if *outputPath == "" {
		output = os.Stdout
	} else {
		file, err := os.OpenFile(*outputPath, os.O_RDWR|os.O_CREATE, 0644)
		output = file
		defer file.Close()
		if err != nil {
			log.Fatalln(err)
		}
	}

	io.Copy(output, generateDontEdit())
	io.Copy(output, r)
}

func generateDontEdit() io.Reader {
	var buffer bytes.Buffer
	fmt.Fprintf(&buffer, "// Code generated by \"string-enumer %s\"; DO NOT EDIT.\n", strings.Join(os.Args[1:], " "))
	return &buffer
}
